# Generated by Django 4.2.3 on 2023-07-20 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_category_alter_event_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
