# Generated by Django 4.2.3 on 2023-07-20 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
